import uuid
from datetime import datetime, timedelta, timezone
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.taxonomy import Constituency, Ministry, District
from app.models.problem import Problem, ProblemTimeline

CONSTITUENCIES_SEED = [
    (1, "Ichchapuram", "Ashok Bendalam"),
    (2, "Palasa", "Gouthu Sireesha"),
    (3, "Tekkali", "Kinjarapu Atchannaidu"),
    (4, "Pathapatnam", "Mamidi Govinda Rao"),
    (5, "Srikakulam", "Gondu Shankar"),
    (6, "Amadalavalasa", "Koona Ravi Kumar"),
    (7, "Etcherla", "Nadukuditi Eswara Rao"),
    (8, "Narasannapeta", "Baggu Ramana Murthy"),
    (9, "Rajam", "Kondru Murali Mohan"),
    (10, "Palakonda", "Nimmaka Jayakrishna"),
    (11, "Kurupam", "Toyaka Jagadeeswari"),
    (12, "Parvathipuram", "Bonela Vijaya Chandra"),
    (13, "Salur", "Gummidi Sandhyarani"),
    (14, "Bobbili", "R.V.S.K.K. Ranga Rao"),
    (15, "Cheepurupalli", "Kimidi Kalavenkata Rao"),
    (16, "Gajapathinagaram", "Kondapalli Srinivas"),
    (17, "Nellimarla", "Lokam Naga Madhavi"),
    (18, "Vizianagaram", "Pusapati Aditi Vijayalakshmi Gajapathi Raju"),
    (19, "Srungavarapukota", "Kolla Lalitha Kumari"),
    (20, "Bhimili", "Ganta Srinivasa Rao"),
    (21, "Visakhapatnam East", "Velagapudi Ramakrishna Babu"),
    (22, "Visakhapatnam South", "Ch. Vamsi Krishna Srinivas"),
    (23, "Visakhapatnam North", "Penmetsa Vishnu Kumar Raju"),
    (24, "Visakhapatnam West", "P.G.V.R. Naidu (Ganababu)"),
    (25, "Gajuwaka", "Palla Srinivasa Rao"),
    (26, "Chodavaram", "Kalidindi Surya Naga Sanyasi Raju"),
    (27, "Madugula", "Bandaru Satyanarayana Murthy"),
    (28, "Araku Valley", "Regam Matyalingam"),
    (29, "Paderu", "Matsyarasa Visweswara Raju"),
    (30, "Anakapalle", "Konathala Ramakrishna"),
    (31, "Pendurthi", "Panchakarla Ramesh Babu"),
    (32, "Yelamanchili", "Sundarapu Vijay Kumar"),
    (33, "Payakaraopeta", "Vangalapudi Anitha"),
    (34, "Narsipatnam", "Chintakayala Ayyanna Patrudu"),
    (35, "Tuni", "Yanamala Divya"),
    (36, "Prathipadu", "Varupula Satya Prabha"),
    (37, "Pithapuram", "Konidela Pawan Kalyan"),
    (38, "Kakinada Rural", "Pantam Venkateswara Rao (Nanaji)"),
    (39, "Peddapuram", "Nimmakayala China Rajappa"),
    (40, "Anaparthy", "Nallamilli Ramakrishna Reddy"),
    (41, "Kakinada City", "Vanamadi Venkateswara Rao (Kondababu)"),
    (42, "Ramachandrapuram", "Vasamsetti Subash"),
    (43, "Mummidivaram", "Datla Subbaraju"),
    (44, "Amalapuram", "Aithabathula Anandarao"),
    (45, "Razole", "Deva Varaprasad"),
    (46, "Gannavaram", "Giddi Satyanarayana"),
    (47, "Kothapeta", "Bandaru Satyananda Rao"),
    (48, "Mandapeta", "Vegulla Jogeswara Rao"),
    (49, "Rajanagaram", "Bathula Balaramakrishna"),
    (50, "Rajahmundry City", "Adireddy Srinivas"),
    (51, "Rajahmundry Rural", "Gorantla Butchaiah Choudary"),
    (52, "Jaggampeta", "Jyothula Nehru"),
    (53, "Rampachodavaram", "Miriyala Sirisha Devi"),
    (54, "Kovvur", "Muppidi Venkateswara Rao"),
    (55, "Nidadavole", "Kandula Durgesh"),
    (56, "Achanta", "Satyanarayana Pithani"),
    (57, "Palacole", "Nimmala Ramanaidu"),
    (58, "Narasapuram", "Bommidi Narayana Nayakar"),
    (59, "Bhimavaram", "Pulaparthi Ramanjaneyulu (Anji Babu)"),
    (60, "Undi", "Kanumuru Raghurama Krishna Raju"),
    (61, "Tanuku", "Arimilli Radha Krishna"),
    (62, "Tadepalligudem", "Bolisetty Srinivas"),
    (63, "Unguturu", "Patsamatla Dharmaraju"),
    (64, "Denduluru", "Chintamaneni Prabhakar"),
    (65, "Eluru", "Badeti Radha Krishnayya"),
    (66, "Gopalapuram", "Maddipati Venkata Raju"),
    (67, "Polavaram", "Chirri Balaraju"),
    (68, "Chintalapudi", "Songa Roshan Kumar"),
    (69, "Tiruvuru", "Kolikapudi Srinivasa Rao"),
    (70, "Nuzvid", "Kolusu Partha Sarathy"),
    (71, "Gannavaram (Krishna)", "Yarlagadda Venkata Rao"),
    (72, "Gudivada", "Venigandla Ramu"),
    (73, "Kaikalur", "Kamineni Srinivas"),
    (74, "Pedana", "Kagitha Krishna Prasad"),
    (75, "Machilipatnam", "Kollu Ravindra"),
    (76, "Avanigadda", "Mandali Buddhaprasad"),
    (77, "Pamarru", "Varla Kumar Raja"),
    (78, "Penamaluru", "Bode Prasad"),
    (79, "Vijayawada West", "Yalamanchili Satyanarayana Chowdary (Sujana Chowdary)"),
    (80, "Vijayawada Central", "Bonda Umamaheswara Rao"),
    (81, "Vijayawada East", "Gadde Rama Mohan"),
    (82, "Mylavaram", "Vasantha Venkata Krishna Prasad"),
    (83, "Nandigama", "Tangirala Sowmya"),
    (84, "Jaggayyapeta", "Sreeram Rajagopal (Tataiah)"),
    (85, "Pedakurapadu", "Bhashyam Praveen"),
    (86, "Tadikonda", "Tenali Sravan Kumar"),
    (87, "Mangalagiri", "Nara Lokesh"),
    (88, "Ponnur", "Dhulipalla Narendra Kumar"),
    (89, "Vemuru", "Nakka Ananda Babu"),
    (90, "Repalle", "Anagani Satya Prasad"),
    (91, "Tenali", "Nadendla Manohar"),
    (92, "Bapatla", "Vegesana Narendra Varma Raju"),
    (93, "Prathipadu (Guntur)", "Burla Ramanjaneyulu"),
    (94, "Guntur West", "Galla Madhavi"),
    (95, "Guntur East", "Mohammed Naseer Ahmed"),
    (96, "Chilakaluripet", "Prathipati Pulla Rao"),
    (97, "Narasaraopet", "Chadalavada Aravinda Babu"),
    (98, "Sattenapalle", "Kanna Lakshminarayana"),
    (99, "Vinukonda", "Gonuguntla Venkata Siva Sita Rama Anjaneyulu"),
    (100, "Gurazala", "Yarapatineni Srinivasa Rao"),
    (101, "Macherla", "Julakanti Brahmananda Reddy"),
    (102, "Yerragondapalem", "Tatiparthi Chandra Sekhar"),
    (103, "Darsi", "Buchepalli Siva Prasad Reddy"),
    (104, "Parchur", "Yeluri Sambasiva Rao"),
    (105, "Addanki", "Gottipati Ravi Kumar"),
    (106, "Chirala", "Madduluri Malakondaiah"),
    (107, "Santhanuthalapadu", "B.N. Vijay Kumar"),
    (108, "Ongole", "Damacharla Janardhana Rao"),
    (109, "Kandukur", "Inturi Nageswara Rao"),
    (110, "Kondapi", "Dola Sree Bala Veeranjaneya Swamy"),
    (111, "Markapuram", "Kandula Narayana Reddy"),
    (112, "Giddalur", "Muthumula Ashok Reddy"),
    (113, "Kanigiri", "Mukku Ugra Narasimha Reddy"),
    (114, "Kavali", "Dagumati Venkata Krishna Reddy"),
    (115, "Atmakur", "Anam Ramanarayana Reddy"),
    (116, "Kovur", "Vemireddy Prashanthi Reddy"),
    (117, "Nellore City", "Ponguru Narayana"),
    (118, "Nellore Rural", "Kotamreddy Sridhar Reddy"),
    (119, "Sarvepalli", "Somireddy Chandramohan Reddy"),
    (120, "Gudur", "Pasim Sunil Kumar"),
    (121, "Sullurpeta", "Nelavala Vijayashree"),
    (122, "Venkatagiri", "Kurugondla Ramakrishna"),
    (123, "Udayagiri", "Kakarl Surendra"),
    (124, "Badvel", "Dasari Sudha"),
    (125, "Rajampet", "Akepati Amarnath Reddy"),
    (126, "Kadapa", "Madhavi Reddappa Gari"),
    (127, "Kodur", "Arava Sreedhar"),
    (128, "Rayachoti", "Mandipalli Ramprasad Reddy"),
    (129, "Pulivendla", "Y.S. Jagan Mohan Reddy"),
    (130, "Kamalapuram", "Putha Krishna Chaitanya Reddy"),
    (131, "Jammalamadugu", "Chadipirala Adinarayana Reddy"),
    (132, "Proddatur", "Nandyala Varada Rajula Reddy"),
    (133, "Mydukur", "Putta Sudhakar Yadav"),
    (134, "Allagadda", "Bhuma Akhila Priya"),
    (135, "Srisailam", "Budda Rajasekhara Reddy"),
    (136, "Nandikotkur", "G. Jayasurya"),
    (137, "Kurnool", "T.G. Bharath"),
    (138, "Panyam", "Gowru Charitha Reddy"),
    (139, "Nandyal", "Nasyam Mohammed Farook"),
    (140, "Banaganapalle", "B.C. Janardhan Reddy"),
    (141, "Dhone", "Kotla Jaya Surya Prakash Reddy"),
    (142, "Pattikonda", "K.E. Shyam Kumar"),
    (143, "Kodumur", "Boggula Dastagiri"),
    (144, "Yemmiganur", "B. Jayanageswara Reddy"),
    (145, "Mantralayam", "Y. Balanagi Reddy"),
    (146, "Adoni", "Partha Sarathi Valmiki"),
    (147, "Alur", "B. Virupakshi"),
    (148, "Rayadurg", "Kalava Srinivasulu"),
    (149, "Uravakonda", "Payyavula Keshav"),
    (150, "Guntakal", "Gummanur Jayaram"),
    (151, "Tadipatri", "J.C. Ashmit Reddy"),
    (152, "Singanamala", "Bandaru Sravani Sree"),
    (153, "Anantapur Urban", "Daggubati Prasad"),
    (154, "Kalyandurg", "Amilineni Surendra Babu"),
    (155, "Raptadu", "Paritala Sunithamma"),
    (156, "Madakasira", "M.S. Raju"),
    (157, "Hindupur", "Nandamuri Balakrishna"),
    (158, "Penukonda", "S. Savitha"),
    (159, "Puttaparthi", "Palle Sindhura Reddy"),
    (160, "Dharmavaram", "Satya Kumar Yadav"),
    (161, "Kadiri", "Kandikunta Venkata Prasad"),
    (162, "Thamballapalle", "P. Dwarakanatha Reddy"),
    (163, "Pileru", "Nallari Kishan Kumar Reddy"),
    (164, "Madanapalle", "M. Shajahan Basha"),
    (165, "Punganur", "Peddireddy Ramachandra Reddy"),
    (166, "Chandragiri", "Pullivarthi Nani"),
    (167, "Tirupati", "Arani Srinivasulu"),
    (168, "Srikalahasti", "Bojjala Venkata Sudhir Reddy"),
    (169, "Satyavedu", "Koneti Adimulam"),
    (170, "Nagari", "Gali Bhanu Prakash"),
    (171, "Gangadhara Nellore", "Dr. V.M. Thomas"),
    (172, "Chittoor", "Gurajala Jagan Mohan"),
    (173, "Puthalapattu", "K. Murali Mohan"),
    (174, "Palamaner", "N. Amaranatha Reddy"),
    (175, "Kuppam", "Nara Chandrababu Naidu"),
]

MINISTRIES_SEED = [
    (1, "General Administration", "N. Chandrababu Naidu"),
    (2, "Law & Order", "N. Chandrababu Naidu"),
    (3, "Public Enterprises", "N. Chandrababu Naidu"),
    (4, "Panchayati Raj", "K. Pawan Kalyan"),
    (5, "Rural Development & Rural Water Supply", "K. Pawan Kalyan"),
    (6, "Environment", "K. Pawan Kalyan"),
    (7, "Forest", "K. Pawan Kalyan"),
    (8, "Science & Technology", "K. Pawan Kalyan"),
    (9, "Human Resources Development", "Nara Lokesh"),
    (10, "IT, Electronics & Communication", "Nara Lokesh"),
    (11, "Real-Time Governance (RTG)", "Nara Lokesh"),
    (12, "Agriculture", "Kinjarapu Atchannaidu"),
    (13, "Co-operation", "Kinjarapu Atchannaidu"),
    (14, "Marketing", "Kinjarapu Atchannaidu"),
    (15, "Animal Husbandry", "Kinjarapu Atchannaidu"),
    (16, "Dairy Development", "Kinjarapu Atchannaidu"),
    (17, "Fisheries", "Kinjarapu Atchannaidu"),
    (18, "Mines & Geology", "Kollu Ravindra"),
    (19, "Excise", "Kollu Ravindra"),
    (20, "Food & Civil Supplies", "Nadendla Manohar"),
    (21, "Consumer Affairs", "Nadendla Manohar"),
    (22, "Municipal Administration & Urban Development", "Ponguru Narayana"),
    (23, "Home Affairs & Disaster Management", "Vangalapudi Anitha"),
    (24, "Health", "Satya Kumar Yadav"),
    (25, "Family Welfare & Medical Education", "Satya Kumar Yadav"),
    (26, "Water Resources Development", "Dr. Nimmala Ramanaidu"),
    (27, "Law & Justice", "Nasyam Mohammed Farook"),
    (28, "Minority Welfare", "Nasyam Mohammed Farook"),
    (29, "Endowments", "Anam Ramanarayana Reddy"),
    (30, "Finance & Planning", "Payyavula Keshav"),
    (31, "Commercial Taxes", "Payyavula Keshav"),
    (32, "Legislative Affairs", "Payyavula Keshav"),
    (33, "Revenue", "Anagani Satya Prasad"),
    (34, "Housing", "Kolusu Parthasarathy"),
    (35, "Information & Public Relations (I&PR)", "Kolusu Parthasarathy"),
    (36, "Social Welfare", "Dola Sree Bala Veeranjaneya Swamy"),
    (37, "Disabled & Senior Citizen Welfare", "Dola Sree Bala Veeranjaneya Swamy"),
    (38, "Sachivalayam & Village Volunteer", "Dola Sree Bala Veeranjaneya Swamy"),
    (39, "Energy", "Gottipati Ravi Kumar"),
    (40, "Tourism", "Kandula Durgesh"),
    (41, "Culture & Cinematography", "Kandula Durgesh"),
    (42, "Women & Child Welfare", "Gummidi Sandhya Rani"),
    (43, "Tribal Welfare", "Gummidi Sandhya Rani"),
    (44, "Roads & Buildings", "B.C. Janardhan Reddy"),
    (45, "Infrastructure & Investments", "B.C. Janardhan Reddy"),
    (46, "Industries & Commerce", "T.G. Bharath"),
    (47, "Food Processing", "T.G. Bharath"),
    (48, "BC Welfare", "S. Savitha"),
    (49, "Economically Weaker Sections Welfare", "S. Savitha"),
    (50, "Handlooms & Textiles", "S. Savitha"),
    (51, "Labour", "Vasamsetti Subhash"),
    (52, "Factories", "Vasamsetti Subhash"),
    (53, "Boilers", "Vasamsetti Subhash"),
    (54, "Insurance Medical Services", "Vasamsetti Subhash"),
    (55, "MSME", "Kondapalli Srinivas"),
    (56, "NRI Empowerment & Relations", "Kondapalli Srinivas"),
    (57, "Society for Elimination of Rural Poverty (SERP)", "Kondapalli Srinivas"),
]

DISTRICTS_SEED = [
    (1, "Alluri Sitharama Raju", "Paderu"),
    (2, "Anakapalli", "Anakapalli"),
    (3, "Ananthapuramu", "Anantapur"),
    (4, "Annamayya", "Rayachoti"),
    (5, "Bapatla", "Bapatla"),
    (6, "Chittoor", "Chittoor"),
    (7, "Dr. B. R. Ambedkar Konaseema", "Amalapuram"),
    (8, "East Godavari", "Rajamahendravaram"),
    (9, "Eluru", "Eluru"),
    (10, "Guntur", "Guntur"),
    (11, "Kakinada", "Kakinada"),
    (12, "Krishna", "Machilipatnam"),
    (13, "Kurnool", "Kurnool"),
    (14, "Markapuram", "Markapuram"),
    (15, "Nandyal", "Nandyal"),
    (16, "NTR", "Vijayawada"),
    (17, "Palnadu", "Narasaraopet"),
    (18, "Parvathipuram Manyam", "Parvathipuram"),
    (19, "Polavaram", "Rampachodavaram"),
    (20, "Prakasam", "Ongole"),
    (21, "Sri Potti Sriramulu Nellore", "Nellore"),
    (22, "Sri Sathya Sai", "Puttaparthi"),
    (23, "Srikakulam", "Srikakulam"),
    (24, "Tirupati", "Tirupati"),
    (25, "Visakhapatnam", "Visakhapatnam"),
    (26, "Vizianagaram", "Vizianagaram"),
    (27, "West Godavari", "Bhimavaram"),
    (28, "Y.S.R. Kadapa", "Kadapa"),
]

INITIAL_PROBLEMS = [
    {
        "id": "AP-2026-0842",
        "title": "Severe craters and waterlogging on Bandar Road junction",
        "description": "Heavy rainfall caused extensive road damage and continuous water stagnation creating severe traffic bottlenecks and 2-wheeler accidents near the junction.",
        "category": "roads",
        "department": "Roads & Buildings",
        "constituency": "Vijayawada East",
        "district": "NTR",
        "area": "Bandar Road Junction, Benz Circle",
        "latitude": 16.5062,
        "longitude": 80.6480,
        "status": "action-initiated",
        "upvotes_count": 48,
        "days_ago": 3,
        "timeline": [
            ("reported", "Problem Reported", "Citizen logged complaint with GPS location."),
            ("under-review", "Ward Inspection", "Local R&B engineer inspected road section."),
            ("action-initiated", "Repair Tender Allocated", "Patchwork work-order issued to municipal contractor."),
        ]
    },
    {
        "id": "AP-2026-0791",
        "title": "Overhead transformer spark hazard and low voltage in Danavaipeta",
        "description": "Frequent sparking on the distribution pole and continuous low voltage causing refrigerator breakdowns across 40+ households.",
        "category": "electricity",
        "department": "Energy",
        "constituency": "Rajahmundry City",
        "district": "East Godavari",
        "area": "Danavaipeta 3rd Street",
        "latitude": 17.0005,
        "longitude": 81.8040,
        "status": "forwarded",
        "upvotes_count": 32,
        "days_ago": 5,
        "timeline": [
            ("reported", "Reported", "Anonymous citizen grievance recorded."),
            ("forwarded", "Transferred to EPDCL", "Ticket assigned to Assistant Engineer, Rajahmundry Town Division."),
        ]
    },
    {
        "id": "AP-2026-0655",
        "title": "Contaminated drinking water supply with sewage odor in Gajuwaka",
        "description": "Municipal tap water has a dark brownish tint and strong sewage smell since Tuesday. Residents are forced to purchase private water cans.",
        "category": "water",
        "department": "Rural Development & Rural Water Supply",
        "constituency": "Gajuwaka",
        "district": "Visakhapatnam",
        "area": "Old Gajuwaka Main Market Area",
        "latitude": 17.6904,
        "longitude": 83.2095,
        "status": "under-review",
        "upvotes_count": 89,
        "days_ago": 2,
        "timeline": [
            ("reported", "Problem Reported", "Report logged with photos."),
            ("under-review", "Water Sample Collected", "GVMC health and water quality team collected samples for lab testing."),
        ]
    },
    {
        "id": "AP-2026-0512",
        "title": "Overflowing open storm drain causing dengue threat in Arundelpet",
        "description": "The open drain has been blocked by plastic waste and silt for 3 weeks, overflowing onto the footpath and breeding mosquitoes.",
        "category": "drainage",
        "department": "Municipal Administration & Urban Development",
        "constituency": "Guntur West",
        "district": "Guntur",
        "area": "Arundelpet 6th Line",
        "latitude": 16.3067,
        "longitude": 80.4365,
        "status": "resolved",
        "upvotes_count": 64,
        "days_ago": 9,
        "timeline": [
            ("reported", "Problem Reported", "Report logged."),
            ("under-review", "Sanitation Team Dispatched", "Ward sanitation inspector visited spot."),
            ("action-initiated", "Excavator Desilting", "Municipal sanitary workers desilted drain."),
            ("resolved", "Cleaned & Verified", "Drain cleared and anti-larval chemical spray completed."),
        ]
    },
    {
        "id": "AP-2026-0418",
        "title": "Broken primary healthcare center refrigeration in Kuppam rural",
        "description": "The vaccine storage unit at the primary health center has been faulty due to power fluctuations, risking vital immunization vials.",
        "category": "health",
        "department": "Health",
        "constituency": "Kuppam",
        "district": "Chittoor",
        "area": "Kuppam Rural PHC",
        "latitude": 12.7533,
        "longitude": 78.3667,
        "status": "action-initiated",
        "upvotes_count": 27,
        "days_ago": 4,
        "timeline": [
            ("reported", "Problem Reported", "Logged anonymously."),
            ("forwarded", "District Medical Officer Alerted", "Ticket escalated to DMHO Chittoor."),
            ("action-initiated", "Solar Backup Inverter Approved", "Sanctioned replacement inverter battery unit."),
        ]
    }
]


async def seed_database(session: AsyncSession) -> None:
    """Populates reference taxonomy tables and initial citizen problems if empty."""
    # 1. Seed Constituencies
    result = await session.execute(select(Constituency).limit(1))
    if not result.scalars().first():
        for cid, name, mla in CONSTITUENCIES_SEED:
            session.add(Constituency(id=cid, name=name, mla=mla))
        await session.flush()

    # 2. Seed Ministries
    result = await session.execute(select(Ministry).limit(1))
    if not result.scalars().first():
        for mid, name, minister in MINISTRIES_SEED:
            session.add(Ministry(id=mid, name=name, minister=minister))
        await session.flush()

    # 3. Seed Districts
    result = await session.execute(select(District).limit(1))
    if not result.scalars().first():
        for did, name, hq in DISTRICTS_SEED:
            session.add(District(id=did, name=name, headquarters=hq))
        await session.flush()

    # 4. Seed Problems
    result = await session.execute(select(Problem).limit(1))
    if not result.scalars().first():
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        for item in INITIAL_PROBLEMS:
            reported_time = now - timedelta(days=item["days_ago"])
            prob = Problem(
                id=item["id"],
                title=item["title"],
                description=item["description"],
                category=item["category"],
                department=item["department"],
                constituency=item["constituency"],
                district=item["district"],
                area=item["area"],
                latitude=item.get("latitude"),
                longitude=item.get("longitude"),
                status=item["status"],
                confirmation_token=str(uuid.uuid4()),
                upvotes_count=item["upvotes_count"],
                reported_at=reported_time,
                updated_at=now,
            )
            session.add(prob)
            await session.flush()

            for step_idx, (st, title, detail) in enumerate(item["timeline"]):
                t_time = reported_time + timedelta(hours=step_idx * 12)
                session.add(
                    ProblemTimeline(
                        problem_id=prob.id,
                        status=st,
                        title=title,
                        detail=detail,
                        timestamp=t_time,
                    )
                )

        await session.commit()
