from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.taxonomy import Constituency, Ministry, District

CONSTITUENCIES_SEED = [
    (1, "Ichchapuram", "Ashok Bendalam Garu"),
    (2, "Palasa", "Gouthu Sireesha Garu"),
    (3, "Tekkali", "Kinjarapu Atchannaidu Garu"),
    (4, "Pathapatnam", "Mamidi Govinda Rao Garu"),
    (5, "Srikakulam", "Gondu Shankar Garu"),
    (6, "Amadalavalasa", "Koona Ravi Kumar Garu"),
    (7, "Etcherla", "Nadukuditi Eswara Rao Garu"),
    (8, "Narasannapeta", "Baggu Ramana Murthy Garu"),
    (9, "Rajam", "Kondru Murali Mohan Garu"),
    (10, "Palakonda", "Nimmaka Jayakrishna Garu"),
    (11, "Kurupam", "Toyaka Jagadeeswari Garu"),
    (12, "Parvathipuram", "Bonela Vijaya Chandra Garu"),
    (13, "Salur", "Gummidi Sandhyarani Garu"),
    (14, "Bobbili", "R.V.S.K.K. Ranga Rao Garu"),
    (15, "Cheepurupalli", "Kimidi Kalavenkata Rao Garu"),
    (16, "Gajapathinagaram", "Kondapalli Srinivas Garu"),
    (17, "Nellimarla", "Lokam Naga Madhavi Garu"),
    (18, "Vizianagaram", "Pusapati Aditi Vijayalakshmi Gajapathi Raju Garu"),
    (19, "Srungavarapukota", "Kolla Lalitha Kumari Garu"),
    (20, "Bhimili", "Ganta Srinivasa Rao Garu"),
    (21, "Visakhapatnam East", "Velagapudi Ramakrishna Babu Garu"),
    (22, "Visakhapatnam South", "Ch. Vamsi Krishna Srinivas Garu"),
    (23, "Visakhapatnam North", "Penmetsa Vishnu Kumar Raju Garu"),
    (24, "Visakhapatnam West", "P.G.V.R. Naidu (Ganababu) Garu"),
    (25, "Gajuwaka", "Palla Srinivasa Rao Garu"),
    (26, "Chodavaram", "Kalidindi Surya Naga Sanyasi Raju Garu"),
    (27, "Madugula", "Bandaru Satyanarayana Murthy Garu"),
    (28, "Araku Valley", "Regam Matyalingam Garu"),
    (29, "Paderu", "Matsyarasa Visweswara Raju Garu"),
    (30, "Anakapalle", "Konathala Ramakrishna Garu"),
    (31, "Pendurthi", "Panchakarla Ramesh Babu Garu"),
    (32, "Yelamanchili", "Sundarapu Vijay Kumar Garu"),
    (33, "Payakaraopeta", "Vangalapudi Anitha Garu"),
    (34, "Narsipatnam", "Chintakayala Ayyanna Patrudu Garu"),
    (35, "Tuni", "Yanamala Divya Garu"),
    (36, "Prathipadu", "Varupula Satya Prabha Garu"),
    (37, "Pithapuram", "Konidela Pawan Kalyan Garu"),
    (38, "Kakinada Rural", "Pantam Venkateswara Rao (Nanaji) Garu"),
    (39, "Peddapuram", "Nimmakayala China Rajappa Garu"),
    (40, "Anaparthy", "Nallamilli Ramakrishna Reddy Garu"),
    (41, "Kakinada City", "Vanamadi Venkateswara Rao (Kondababu) Garu"),
    (42, "Ramachandrapuram", "Vasamsetti Subash Garu"),
    (43, "Mummidivaram", "Datla Subbaraju Garu"),
    (44, "Amalapuram", "Aithabathula Anandarao Garu"),
    (45, "Razole", "Deva Varaprasad Garu"),
    (46, "Gannavaram", "Giddi Satyanarayana Garu"),
    (47, "Kothapeta", "Bandaru Satyananda Rao Garu"),
    (48, "Mandapeta", "Vegulla Jogeswara Rao Garu"),
    (49, "Rajanagaram", "Bathula Balaramakrishna Garu"),
    (50, "Rajahmundry City", "Adireddy Srinivas Garu"),
    (51, "Rajahmundry Rural", "Gorantla Butchaiah Choudary Garu"),
    (52, "Jaggampeta", "Jyothula Nehru Garu"),
    (53, "Rampachodavaram", "Miriyala Sirisha Devi Garu"),
    (54, "Kovvur", "Muppidi Venkateswara Rao Garu"),
    (55, "Nidadavole", "Kandula Durgesh Garu"),
    (56, "Achanta", "Satyanarayana Pithani Garu"),
    (57, "Palacole", "Nimmala Ramanaidu Garu"),
    (58, "Narasapuram", "Bommidi Narayana Nayakar Garu"),
    (59, "Bhimavaram", "Pulaparthi Ramanjaneyulu (Anji Babu) Garu"),
    (60, "Undi", "Kanumuru Raghurama Krishna Raju Garu"),
    (61, "Tanuku", "Arimilli Radha Krishna Garu"),
    (62, "Tadepalligudem", "Bolisetty Srinivas Garu"),
    (63, "Unguturu", "Patsamatla Dharmaraju Garu"),
    (64, "Denduluru", "Chintamaneni Prabhakar Garu"),
    (65, "Eluru", "Badeti Radha Krishnayya Garu"),
    (66, "Gopalapuram", "Maddipati Venkata Raju Garu"),
    (67, "Polavaram", "Chirri Balaraju Garu"),
    (68, "Chintalapudi", "Songa Roshan Kumar Garu"),
    (69, "Tiruvuru", "Kolikapudi Srinivasa Rao Garu"),
    (70, "Nuzvid", "Kolusu Partha Sarathy Garu"),
    (71, "Gannavaram (Krishna)", "Yarlagadda Venkata Rao Garu"),
    (72, "Gudivada", "Venigandla Ramu Garu"),
    (73, "Kaikalur", "Kamineni Srinivas Garu"),
    (74, "Pedana", "Kagitha Krishna Prasad Garu"),
    (75, "Machilipatnam", "Kollu Ravindra Garu"),
    (76, "Avanigadda", "Mandali Buddhaprasad Garu"),
    (77, "Pamarru", "Varla Kumar Raja Garu"),
    (78, "Penamaluru", "Bode Prasad Garu"),
    (79, "Vijayawada West", "Yalamanchili Satyanarayana Chowdary (Sujana Chowdary) Garu"),
    (80, "Vijayawada Central", "Bonda Umamaheswara Rao Garu"),
    (81, "Vijayawada East", "Gadde Rama Mohan Garu"),
    (82, "Mylavaram", "Vasantha Venkata Krishna Prasad Garu"),
    (83, "Nandigama", "Tangirala Sowmya Garu"),
    (84, "Jaggayyapeta", "Sreeram Rajagopal (Tataiah) Garu"),
    (85, "Pedakurapadu", "Bhashyam Praveen Garu"),
    (86, "Tadikonda", "Tenali Sravan Kumar Garu"),
    (87, "Mangalagiri", "Nara Lokesh Garu"),
    (88, "Ponnur", "Dhulipalla Narendra Kumar Garu"),
    (89, "Vemuru", "Nakka Ananda Babu Garu"),
    (90, "Repalle", "Anagani Satya Prasad Garu"),
    (91, "Tenali", "Nadendla Manohar Garu"),
    (92, "Bapatla", "Vegesana Narendra Varma Raju Garu"),
    (93, "Prathipadu (Guntur)", "Burla Ramanjaneyulu Garu"),
    (94, "Guntur West", "Galla Madhavi Garu"),
    (95, "Guntur East", "Mohammed Naseer Ahmed Garu"),
    (96, "Chilakaluripet", "Prathipati Pulla Rao Garu"),
    (97, "Narasaraopet", "Chadalavada Aravinda Babu Garu"),
    (98, "Sattenapalle", "Kanna Lakshminarayana Garu"),
    (99, "Vinukonda", "Gonuguntla Venkata Siva Sita Rama Anjaneyulu Garu"),
    (100, "Gurazala", "Yarapatineni Srinivasa Rao Garu"),
    (101, "Macherla", "Julakanti Brahmananda Reddy Garu"),
    (102, "Yerragondapalem", "Tatiparthi Chandra Sekhar Garu"),
    (103, "Darsi", "Buchepalli Siva Prasad Reddy Garu"),
    (104, "Parchur", "Yeluri Sambasiva Rao Garu"),
    (105, "Addanki", "Gottipati Ravi Kumar Garu"),
    (106, "Chirala", "Madduluri Malakondaiah Garu"),
    (107, "Santhanuthalapadu", "B.N. Vijay Kumar Garu"),
    (108, "Ongole", "Damacharla Janardhana Rao Garu"),
    (109, "Kandukur", "Inturi Nageswara Rao Garu"),
    (110, "Kondapi", "Dola Sree Bala Veeranjaneya Swamy Garu"),
    (111, "Markapuram", "Kandula Narayana Reddy Garu"),
    (112, "Giddalur", "Muthumula Ashok Reddy Garu"),
    (113, "Kanigiri", "Mukku Ugra Narasimha Reddy Garu"),
    (114, "Kavali", "Dagumati Venkata Krishna Reddy Garu"),
    (115, "Atmakur", "Anam Ramanarayana Reddy Garu"),
    (116, "Kovur", "Vemireddy Prashanthi Reddy Garu"),
    (117, "Nellore City", "Ponguru Narayana Garu"),
    (118, "Nellore Rural", "Kotamreddy Sridhar Reddy Garu"),
    (119, "Sarvepalli", "Somireddy Chandramohan Reddy Garu"),
    (120, "Gudur", "Pasim Sunil Kumar Garu"),
    (121, "Sullurpeta", "Nelavala Vijayashree Garu"),
    (122, "Venkatagiri", "Kurugondla Ramakrishna Garu"),
    (123, "Udayagiri", "Kakarl Surendra Garu"),
    (124, "Badvel", "Dasari Sudha Garu"),
    (125, "Rajampet", "Akepati Amarnath Reddy Garu"),
    (126, "Kadapa", "Madhavi Reddappa Gari"),
    (127, "Kodur", "Arava Sreedhar Garu"),
    (128, "Rayachoti", "Mandipalli Ramprasad Reddy Garu"),
    (129, "Pulivendla", "Y.S. Jagan Mohan Reddy Garu"),
    (130, "Kamalapuram", "Putha Krishna Chaitanya Reddy Garu"),
    (131, "Jammalamadugu", "Chadipirala Adinarayana Reddy Garu"),
    (132, "Proddatur", "Nandyala Varada Rajula Reddy Garu"),
    (133, "Mydukur", "Putta Sudhakar Yadav Garu"),
    (134, "Allagadda", "Bhuma Akhila Priya Garu"),
    (135, "Srisailam", "Budda Rajasekhara Reddy Garu"),
    (136, "Nandikotkur", "G. Jayasurya Garu"),
    (137, "Kurnool", "T.G. Bharath Garu"),
    (138, "Panyam", "Gowru Charitha Reddy Garu"),
    (139, "Nandyal", "Nasyam Mohammed Farook Garu"),
    (140, "Banaganapalle", "B.C. Janardhan Reddy Garu"),
    (141, "Dhone", "Kotla Jaya Surya Prakash Reddy Garu"),
    (142, "Pattikonda", "K.E. Shyam Kumar Garu"),
    (143, "Kodumur", "Boggula Dastagiri Garu"),
    (144, "Yemmiganur", "B. Jayanageswara Reddy Garu"),
    (145, "Mantralayam", "Y. Balanagi Reddy Garu"),
    (146, "Adoni", "Partha Sarathi Valmiki Garu"),
    (147, "Alur", "B. Virupakshi Garu"),
    (148, "Rayadurg", "Kalava Srinivasulu Garu"),
    (149, "Uravakonda", "Payyavula Keshav Garu"),
    (150, "Guntakal", "Gummanur Jayaram Garu"),
    (151, "Tadipatri", "J.C. Ashmit Reddy Garu"),
    (152, "Singanamala", "Bandaru Sravani Sree Garu"),
    (153, "Anantapur Urban", "Daggubati Prasad Garu"),
    (154, "Kalyandurg", "Amilineni Surendra Babu Garu"),
    (155, "Raptadu", "Paritala Sunithamma Garu"),
    (156, "Madakasira", "M.S. Raju Garu"),
    (157, "Hindupur", "Nandamuri Balakrishna Garu"),
    (158, "Penukonda", "S. Savitha Garu"),
    (159, "Puttaparthi", "Palle Sindhura Reddy Garu"),
    (160, "Dharmavaram", "Satya Kumar Yadav Garu"),
    (161, "Kadiri", "Kandikunta Venkata Prasad Garu"),
    (162, "Thamballapalle", "P. Dwarakanatha Reddy Garu"),
    (163, "Pileru", "Nallari Kishan Kumar Reddy Garu"),
    (164, "Madanapalle", "M. Shajahan Basha Garu"),
    (165, "Punganur", "Peddireddy Ramachandra Reddy Garu"),
    (166, "Chandragiri", "Pullivarthi Nani Garu"),
    (167, "Tirupati", "Arani Srinivasulu Garu"),
    (168, "Srikalahasti", "Bojjala Venkata Sudhir Reddy Garu"),
    (169, "Satyavedu", "Koneti Adimulam Garu"),
    (170, "Nagari", "Gali Bhanu Prakash Garu"),
    (171, "Gangadhara Nellore", "Dr. V.M. Thomas Garu"),
    (172, "Chittoor", "Gurajala Jagan Mohan Garu"),
    (173, "Puthalapattu", "K. Murali Mohan Garu"),
    (174, "Palamaner", "N. Amaranatha Reddy Garu"),
    (175, "Kuppam", "Nara Chandrababu Naidu Garu"),
]

MINISTRIES_SEED = [
    (1, "General Administration", "N. Chandrababu Naidu Garu"),
    (2, "Law & Order", "N. Chandrababu Naidu Garu"),
    (3, "Public Enterprises", "N. Chandrababu Naidu Garu"),
    (4, "Panchayati Raj", "K. Pawan Kalyan Garu"),
    (5, "Rural Development & Rural Water Supply", "K. Pawan Kalyan Garu"),
    (6, "Environment", "K. Pawan Kalyan Garu"),
    (7, "Forest", "K. Pawan Kalyan Garu"),
    (8, "Science & Technology", "K. Pawan Kalyan Garu"),
    (9, "Human Resources Development", "Nara Lokesh Garu"),
    (10, "IT, Electronics & Communication", "Nara Lokesh Garu"),
    (11, "Real-Time Governance (RTG)", "Nara Lokesh Garu"),
    (12, "Agriculture", "Kinjarapu Atchannaidu Garu"),
    (13, "Co-operation", "Kinjarapu Atchannaidu Garu"),
    (14, "Marketing", "Kinjarapu Atchannaidu Garu"),
    (15, "Animal Husbandry", "Kinjarapu Atchannaidu Garu"),
    (16, "Dairy Development", "Kinjarapu Atchannaidu Garu"),
    (17, "Fisheries", "Kinjarapu Atchannaidu Garu"),
    (18, "Mines & Geology", "Kollu Ravindra Garu"),
    (19, "Excise", "Kollu Ravindra Garu"),
    (20, "Food & Civil Supplies", "Nadendla Manohar Garu"),
    (21, "Consumer Affairs", "Nadendla Manohar Garu"),
    (22, "Municipal Administration & Urban Development", "Ponguru Narayana Garu"),
    (23, "Home Affairs & Disaster Management", "Vangalapudi Anitha Garu"),
    (24, "Health", "Satya Kumar Yadav Garu"),
    (25, "Family Welfare & Medical Education", "Satya Kumar Yadav Garu"),
    (26, "Water Resources Development", "Dr. Nimmala Ramanaidu Garu"),
    (27, "Law & Justice", "Nasyam Mohammed Farook Garu"),
    (28, "Minority Welfare", "Nasyam Mohammed Farook Garu"),
    (29, "Endowments", "Anam Ramanarayana Reddy Garu"),
    (30, "Finance & Planning", "Payyavula Keshav Garu"),
    (31, "Commercial Taxes", "Payyavula Keshav Garu"),
    (32, "Legislative Affairs", "Payyavula Keshav Garu"),
    (33, "Revenue", "Anagani Satya Prasad Garu"),
    (34, "Housing", "Kolusu Parthasarathy Garu"),
    (35, "Information & Public Relations (I&PR)", "Kolusu Parthasarathy Garu"),
    (36, "Social Welfare", "Dola Sree Bala Veeranjaneya Swamy Garu"),
    (37, "Disabled & Senior Citizen Welfare", "Dola Sree Bala Veeranjaneya Swamy Garu"),
    (38, "Sachivalayam & Village Volunteer", "Dola Sree Bala Veeranjaneya Swamy Garu"),
    (39, "Energy", "Gottipati Ravi Kumar Garu"),
    (40, "Tourism", "Kandula Durgesh Garu"),
    (41, "Culture & Cinematography", "Kandula Durgesh Garu"),
    (42, "Women & Child Welfare", "Gummidi Sandhya Rani Garu"),
    (43, "Tribal Welfare", "Gummidi Sandhya Rani Garu"),
    (44, "Roads & Buildings", "B.C. Janardhan Reddy Garu"),
    (45, "Infrastructure & Investments", "B.C. Janardhan Reddy Garu"),
    (46, "Industries & Commerce", "T.G. Bharath Garu"),
    (47, "Food Processing", "T.G. Bharath Garu"),
    (48, "BC Welfare", "S. Savitha Garu"),
    (49, "Economically Weaker Sections Welfare", "S. Savitha Garu"),
    (50, "Handlooms & Textiles", "S. Savitha Garu"),
    (51, "Labour", "Vasamsetti Subhash Garu"),
    (52, "Factories", "Vasamsetti Subhash Garu"),
    (53, "Boilers", "Vasamsetti Subhash Garu"),
    (54, "Insurance Medical Services", "Vasamsetti Subhash Garu"),
    (55, "MSME", "Kondapalli Srinivas Garu"),
    (56, "NRI Empowerment & Relations", "Kondapalli Srinivas Garu"),
    (57, "Society for Elimination of Rural Poverty (SERP)", "Kondapalli Srinivas Garu"),
]

DISTRICTS_SEED = [
    (1, "Alluri Sitharama Raju", "Paderu"),
    (2, "Anakapalli", "Anakapalli"),
    (3, "Ananthapuramu", "Anantapur"),
    (4, "Annamayya", "Rayachoti"),
    (5, "Bapatla", "Bapatla"),
    (6, "Chittoor", "Chittoor"),
    (7, "Dr. B.R. Ambedkar Konaseema", "Amalapuram"),
    (8, "East Godavari", "Rajahmundry"),
    (9, "Eluru", "Eluru"),
    (10, "Guntur", "Guntur"),
    (11, "Kakinada", "Kakinada"),
    (12, "Krishna", "Machilipatnam"),
    (13, "Kurnool", "Kurnool"),
    (14, "Nandyal", "Nandyal"),
    (15, "NTR", "Vijayawada"),
    (16, "Palnadu", "Narasaraopet"),
    (17, "Parvathipuram Manyam", "Parvathipuram"),
    (18, "Prakasam", "Ongole"),
    (19, "Sri Potti Sriramulu Nellore", "Nellore"),
    (20, "Sri Sathya Sai", "Puttaparthi"),
    (21, "Tirupati", "Tirupati"),
    (22, "Visakhapatnam", "Visakhapatnam"),
    (23, "Vizianagaram", "Vizianagaram"),
    (24, "West Godavari", "Bhimavaram"),
    (25, "Y.S.R. Kadapa", "Kadapa"),
    (26, "Srikakulam", "Srikakulam"),
    (27, "Amaravati", "Amaravati"),
    (28, "Polavaram", "Polavaram"),
]

async def seed_database(session: AsyncSession) -> None:
    """Populates reference taxonomy tables (Constituencies, Ministries, Districts) without any mock problems."""
    # 1. Seed / Update Constituencies
    result = await session.execute(select(Constituency))
    existing_const = result.scalars().all()
    if not existing_const:
        for cid, name, mla in CONSTITUENCIES_SEED:
            session.add(Constituency(id=cid, name=name, mla=mla))
        await session.flush()
    else:
        for c in existing_const:
            for cid, name, mla in CONSTITUENCIES_SEED:
                if c.id == cid:
                    c.mla = mla
                    break
        await session.flush()

    # 2. Seed / Update Ministries
    result = await session.execute(select(Ministry))
    existing_min = result.scalars().all()
    if not existing_min:
        for mid, name, minister in MINISTRIES_SEED:
            session.add(Ministry(id=mid, name=name, minister=minister))
        await session.flush()
    else:
        for m in existing_min:
            for mid, name, minister in MINISTRIES_SEED:
                if m.id == mid:
                    m.minister = minister
                    break
        await session.flush()

    # 3. Seed Districts
    result = await session.execute(select(District).limit(1))
    if not result.scalars().first():
        for did, name, hq in DISTRICTS_SEED:
            session.add(District(id=did, name=name, headquarters=hq))
        await session.flush()

    await session.commit()
